version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
    - krivahtoo
  assignees:
    - krivahtoo
  commit-message:
    prefix: build
    prefix-development: chore
    include: scope
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
